cpu:
  svd: stm32f407.svd
  vector_table: 0x08008000
  #id: 0x1234_5678_BABE_1234_5678_BABE
regions:
  - name: NULL_forgiveness
    start: 0x00000000
    size: 4096
  - name: ROM
    start: 0x08000000
    load: fw_v3.5.4.bin
    size: 0x80000
  - name: RAM-CCM
    start: 0x10000000
    size: 0x18000
  - name: RAM
    start: 0x20000000
    size: 0x20000
devices:
  sw_spi:
    - name: LCD_SPI
      cs: PA15
      clk: PC7
      miso: PC6
      mosi: PG3
  spi_flash:
    - peripheral: SPI2
      jedec_id: 0xef4016
      file: PMS_UI_001.bin
      size: 0x2000000
  display:
    - peripheral: FSMC.BANK1
      width: 480
      height: 320
      cmd_addr_bit: 0x20000
      swap_bytes: true
  lcd:
    - peripheral: SPI1
      width: 3840
      height: 2400
patches:
  # NOP systick delay
  - start: 0x0800b656
    data: [0x70, 0x47]
  # NOP delay_cycle
  - start: 0x0800d434
    data: [0x70, 0x47]
  # NOP display drawing
  # - start: 0x08018b58
  #  data: [0x70, 0x47]
  # NOP LCD init drawing
  # - start: 0x0800e4da
  #   data: [0x70, 0x47]
